In [1]:
import pandas as pd
import numpy as np
import regex as re
import matplotlib.pyplot as plt
import seaborn as sns
from functions import ratingsearch
from functions import priceapp
from functions import currency

In [2]:
apps = pd.read_csv("/Users/Carlos/Desktop/Ironhack/REPOS/proyecto/storytelling-project/Data/msft.csv")

### Aquí tenemos nuestra tabla de datos, compuesta por una lista de apps, con sus reviews, fecha, categoría y precio

In [3]:
apps

,Name,Rating,No of people Rated,Category,Date,Price
0,Dynamic Reader,3.5,268,Books,07-01-2014,Free
1,"Chemistry, Organic Chemistry and Biochemistry-...",3.0,627,Books,08-01-2014,Free
2,BookViewer,3.5,593,Books,29-02-2016,Free
3,Brick Instructions,3.5,684,Books,30-01-2018,Free
4,Introduction to Python Programming by GoLearni...,2.0,634,Books,30-01-2018,Free
...,...,...,...,...,...,...
5317,JS King,1.0,720,Developer Tools,19-07-2018,₹ 269.00
5318,MQTTSniffer,2.5,500,Developer Tools,10-04-2017,₹ 64.00
5319,"Dev Utils - JSON, CSV and XML",4.0,862,Developer Tools,18-11-2019,₹ 269.00
5320,Simply Text,4.0,386,Developer Tools,23-01-2014,₹ 219.00
5321,NaN,NaN,948,NaN,NaN,NaN

### Lo primero, vamos a quitar los valores nulos de esta tabla, para facilitar la limpieza.

In [4]:
apps = apps.dropna()

### Aquí he calculado una nueva columna, en la que se representa el numero de personas que han hecho el review, multiplicado por la review que han hecho, dándonos una cifra más representativa de las reviews.

In [5]:
apps["Total Rating"]= apps.Rating * apps["No of people Rated"]

<ipython-input-5-93b067aa4bd2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  apps["Total Rating"]= apps.Rating * apps["No of people Rated"]

In [6]:
apps.sort_values(["Total Rating"],ascending=False).head(20)

,Name,Rating,No of people Rated,Category,Date,Price,Total Rating
1883,ILN,5.0,999,Social,05-12-2019,Free,4995.0
319,TookBook,5.0,998,Books,26-06-2018,Free,4990.0
3406,Contemplatio - Rosary with images,5.0,998,Lifestyle,13-08-2018,Free,4990.0
3241,Five Good Things,5.0,996,Lifestyle,16-10-2016,Free,4980.0
2662,Magenta Health,5.0,993,Health and Fitness,28-02-2016,Free,4965.0
1469,BIOSToolKit,5.0,989,Developer Tools,26-07-2018,Free,4945.0
2038,Parents Worship Day,5.0,988,Social,09-02-2015,Free,4940.0
252,Ask Sai,5.0,988,Books,17-04-2011,Free,4940.0
5305,Littledot,5.0,987,Developer Tools,23-03-2019,₹ 79.00,4935.0
4653,See Tow Bus,5.0,986,Navigation and Maps,25-10-2018,Free,4930.0
2497,EMS Monitoring Studio,5.0,985,Health and Fitness,14-06-2019,Free,4925.0
944,Jot ERP,5.0,984,Business,09-11-2016,Free,4920.0
2567,STOPP app,5.0,984,Health and Fitness,26-08-2016,Free,4920.0
951,Black Scholes Calculator,5.0,983,Business,27-02-2016,Free,4915.0
3851,MP3 Volume Booster,5.0,982,Music,25-02-2020,Free,4910.0
1681,Enterprise Mobility News,5.0,982,Developer Tools,24-02-2016,Free,4910.0
521,Lilith story,5.0,981,Books,28-02-2017,Free,4905.0
2639,Abs boot camp island game,5.0,981,Health and Fitness,20-07-2017,Free,4905.0
1551,TPM Return Code Decoder,5.0,981,Developer Tools,26-04-2016,Free,4905.0
1534,Tabnalysis,5.0,981,Developer Tools,19-09-2017,Free,4905.0

#### Luego, convertí el precio (Rupias indias) en euros, para poder representarlo en gráficas y que sea más facil de operar.

In [7]:
apps["Price"] = apps.Price.apply(lambda x: x.replace(",",""))

<ipython-input-7-339af3437c67>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  apps["Price"] = apps.Price.apply(lambda x: x.replace(",",""))

In [8]:
apps["Price"] = apps["Price"].apply(currency)

<ipython-input-8-8f1ea9dcbed6>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  apps["Price"] = apps["Price"].apply(currency)

In [10]:
apps

,Name,Rating,No of people Rated,Category,Date,Price,Total Rating
0,Dynamic Reader,3.5,268,Books,07-01-2014,0.000,938.0
1,"Chemistry, Organic Chemistry and Biochemistry-...",3.0,627,Books,08-01-2014,0.000,1881.0
2,BookViewer,3.5,593,Books,29-02-2016,0.000,2075.5
3,Brick Instructions,3.5,684,Books,30-01-2018,0.000,2394.0
4,Introduction to Python Programming by GoLearni...,2.0,634,Books,30-01-2018,0.000,1268.0
...,...,...,...,...,...,...,...
5316,Get Color,3.0,785,Developer Tools,08-08-2019,0.654,2355.0
5317,JS King,1.0,720,Developer Tools,19-07-2018,3.228,720.0
5318,MQTTSniffer,2.5,500,Developer Tools,10-04-2017,0.768,1250.0
5319,"Dev Utils - JSON, CSV and XML",4.0,862,Developer Tools,18-11-2019,3.228,3448.0
5320,Simply Text,4.0,386,Developer Tools,23-01-2014,2.628,1544.0

#### Por último para la limpieza, he creado varias funciones, para facilitar la búsqueda de los datos.

In [12]:
ratingsearch(4)

,Name,Rating,No of people Rated,Category,Date,Price
8,ACK Comics,4.0,460.0,Books,20-12-2012,Free
10,Coding Made Easy - SQL,4.0,774.0,Books,30-01-2018,Free
11,Baani : Nitnem,4.0,533.0,Books,29-08-2014,Free
12,iMac® 101,4.0,707.0,Books,28-03-2014,Free
13,Complete C Programs,4.0,687.0,Books,07-12-2012,Free
...,...,...,...,...,...,...
5295,RocketCake Professional,4.0,691.0,Developer Tools,08-12-2016,"₹ 2,149.00"
5310,EditPlus,4.0,778.0,Developer Tools,27-09-2016,"₹ 1,899.00"
5311,0x Hex Viewer,4.0,211.0,Developer Tools,20-02-2016,₹ 54.00
5319,"Dev Utils - JSON, CSV and XML",4.0,862.0,Developer Tools,18-11-2019,₹ 269.00
5320,Simply Text,4.0,386.0,Developer Tools,23-01-2014,₹ 219.00

In [19]:
priceapp("EditPlus")

   index       Price
0   5310  ₹ 1,899.00

In [14]:
apps_clean = apps

In [17]:
apps_clean

,Name,Rating,No of people Rated,Category,Date,Price,Total Rating
0,Dynamic Reader,3.5,268,Books,07-01-2014,0.000,938.0
1,"Chemistry, Organic Chemistry and Biochemistry-...",3.0,627,Books,08-01-2014,0.000,1881.0
2,BookViewer,3.5,593,Books,29-02-2016,0.000,2075.5
3,Brick Instructions,3.5,684,Books,30-01-2018,0.000,2394.0
4,Introduction to Python Programming by GoLearni...,2.0,634,Books,30-01-2018,0.000,1268.0
...,...,...,...,...,...,...,...
5316,Get Color,3.0,785,Developer Tools,08-08-2019,0.654,2355.0
5317,JS King,1.0,720,Developer Tools,19-07-2018,3.228,720.0
5318,MQTTSniffer,2.5,500,Developer Tools,10-04-2017,0.768,1250.0
5319,"Dev Utils - JSON, CSV and XML",4.0,862,Developer Tools,18-11-2019,3.228,3448.0
5320,Simply Text,4.0,386,Developer Tools,23-01-2014,2.628,1544.0

In [18]:
apps_clean.to_csv(r"/Users/Carlos/Desktop/Ironhack/REPOS/proyecto/storytelling-project/DataFile apps_clean.csv")